site_name: Tishenko's knowledge base
site_url: https://kb.tishenko.dev
theme:
  name: material
  favicon: assets/favicon.ico
  
  features:
    - navigation.instant
    - navigation.tabs

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false