name: Build MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        run: |
          git clone --depth 1 --branch main https://git.tishenko.dev/tish/knowledge-base.git

      - name: Build site
        run: |
          cd knowledge-base
          pip install -r requirements.txt
          mkdocs build

      - name: Deploy site
        run: |
          # Удаляем только содержимое /var/www/knowledge-base,
          # чтобы сохранить права и владельца самой папки
          cd knowledge-base
          rm -rf /var/www/knowledge-base/*
          cp -r site/ /var/www/knowledge-base/site/
