name: Build MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy files to deployment folder
        run: |
          rm -rf /var/www/knowledge-base/*
          cp -r . /var/www/knowledge-base

      - name: Build site
        run: |
          cd /var/www/knowledge-base
          mkdocs build
