name: Build MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    container:
      image: python:3.12-slim
      options: --volume /var/www/knowledge-base:/var/www/knowledge-base
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git

      - name: Checkout repository
        run: |
          git clone --depth 1 --branch main https://git.tishenko.dev/tish/knowledge-base.git

      - name: Build site
        run: |
          cd knowledge-base
          pip install -r requirements.txt
          mkdocs build

      - name: Deploy site
        run: |
          cd knowledge-base
          # Удаляем старую версию сайта
          rm -rf /var/www/knowledge-base/site
          # Копируем новую
          cp -r site/ /var/www/knowledge-base/site/
