name: Build MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Clean up old repo in /tmp
        run: |
          rm -rf /tmp/knowledge-base

      - name: Clone repository
        run: |
          pwd
          git clone --branch main https://git.tishenko.dev/tish/knowledge-base.git

      - name: Build site
        run: |
          mkdocs build

      - name: Deploy site
        run: |
          # Удаляем только содержимое /var/www/knowledge-base,
          # чтобы сохранить права и владельца самой папки
          rm -rf /var/www/knowledge-base/*
          cp -r site/ /var/www/knowledge-base/site/
